version: '3.4'

services:

  hotel-cmd-consumer:
    image: hotel-cmd-side
    container_name: hotel-cmd-side
    build:
      context: .
      dockerfile: Hotel.Cmd/Hotel.Cmd.Consumer/Dockerfile
    tty: true
    stdin_open: true
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_QUEUE=hotelCommandQueue
      - MONGO_USER=root
      - MONGO_PASSWORD=123
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=Hotel
      - MONGO_COLLECTION=eventStore
      - KAFKA_HOST=broker
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=hotelEvents
    restart: always
    depends_on:
      - mongo
      - rabbitmq
      - broker

  hotel-query-consumer:
    image: hotel-query-side
    container_name: hotel-query-consumer
    build:
      context: .
      dockerfile: Hotel.Query/Hotel.Query.Consumer/Dockerfile
    tty: true
    stdin_open: true
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_QUEUE=hotelCommandQueue
      - KAFKA_HOST=broker
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=hotelEvents
      - KAFKA_GROUP_ID=Hotel_Consumer
      - KAFKA_AUTO_OFFSET_RESET=Earliest
      - KAFKA_ENABLE_AUTO_COMMIT=false
      - KAFKA_ALLOW_AUTO_CREATE_TOPICS=true
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DATABASE=HotelDB
    restart: always
    depends_on:
      - postgres
      - rabbitmq
      - broker

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - mongo_database:/data/db:rw
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    container_name: express
    hostname: express
    ports:
      - 30001:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_URL=mongodb://root:123@mongo:27017/

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    restart: always
    volumes:
      - rabbit_database:/var/lib/rabbitmq:rw
    ports:
      - "5672:5672"
      - "15672:15672"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  broker:
    image: confluentinc/cp-kafka:5.5.0
    container_name: broker
    hostname: broker
    restart: always
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_database:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - 30000:8080

volumes:
  mongo_database:
  rabbit_database:
  postgres_database:
